version: 2.1

defaults: &defaults
  working_directory: ~/auto
  docker:
    - image: circleci/node:10-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - add_ssh_keys:
          fingerprints:
            - "22:1b:d1:7e:6d:3d:0e:2a:8d:af:81:48:aa:61:ed:2a"
      - run:
          name: Release
          command: yarn auto shipit -vv


workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - release:
          requires:
            - install
